#!/usr/bin/env bash	
set -e # Exit on any child process error

npm run clean

mkdir -p dist

echo "Transpile ES6 to CJS"
npm install
npm run transpile -- --ignore spec.js

echo "Processing infrastructure template for $DRONE_BRANCH"

cat ./infrastructure/constants/$DRONE_BRANCH.json > ./dist/constants.json
cat ./dist/constants.json | mustache - ./infrastructure/cloudformation.yaml > ./dist/cloudformation.yaml
cat ./dist/constants.json | mustache - ./infrastructure/swagger.yaml > ./dist/swagger.yaml

echo "Production NPM Install"
rm -rf ./node_modules
npm install --production

pushd ./dist/cjs
ln -s ../../node_modules/
popd

echo "Packaging Code"
pushd dist/cjs
zip -q -r ../domino-master-backend-api.zip .
